project:
  type: website
  output-dir: docs

website:
  title: "Rui-Yang Zhang"
  favicon: rui.svg
  navbar:
    logo: rui.svg
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: notes.qmd
        text: Notes
      - href: resources.qmd
        text: Resources
      - href: blog.qmd
        text: Blog
  
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

